const books = [
	{
		id: 1,
		name: "Crime e Castigo",
		author: { _name: "Fiódor Dostoiévski" },
		coverPath: "/assets/book-covers/crime-e-castigo.png",
		price: 49.9,

		resume:
			"Raskólnikov, um jovem ex-estudante de direito em São Petersburgo, vive em extrema pobreza. Atormentado por teorias sobre crime e moralidade, ele assassina uma velha agiota e sua irmã. O romance acompanha sua luta psicológica após o crime, explorando temas de culpa, redenção e a natureza do bem e do mal. Através do relacionamento com Sônia, uma jovem prostituída de coração puro, Raskólnikov embarca em uma jornada de autoconhecimento e possível salvação.",
		isbn: "978-85-359-0277-3",
		numberOfPages: 672,
		categories: ["Literatura Clássica"],
		year: 1866,
		edition: "1a. edição",
		publisher: { _description: "Companhia das Letras" },
		height: 21.0,
		width: 14.0,
		weight: 0.6,
		thickness: 3.5,
		barCode: "9788535902773",
		inactivationCause: "",
		activationCause: "Lançamento",
		stockQuantity: 25,
	},
	{
		id: 2,
		name: "Hipótese do Amor",
		author: { _name: "Ali Hazelwood" },
		coverPath: "/assets/book-covers/hipotese-do-amor.png",
		price: 39.9,

		resume:
			"Olive Smith é uma doutoranda em biologia de Stanford que não acredita em relacionamentos duradouros. Quando precisa convencer sua melhor amiga de que está feliz em um relacionamento, ela beija um estranho no laboratório. O problema é que esse estranho é Adam Carlsen, um jovem professor conhecido por sua personalidade difícil. Para surpresa de ambos, Adam concorda em fingir um namoro, mas o que começou como uma farsa pode se tornar algo muito real.",
		isbn: "978-65-5560-622-8",
		numberOfPages: 384,
		categories: ["Romance Moderno"],
		year: 2021,
		edition: "2a. edição",
		publisher: { _description: "Arqueiro" },
		height: 20.5,
		width: 13.5,
		weight: 0.4,
		thickness: 2.0,
		barCode: "9786555606228",
		inactivationCause: "",
		activationCause: "Lançamento",
		stockQuantity: 15,
	},
	{
		id: 3,
		name: "O Senhor dos Anéis",
		author: { _name: "J.R.R. Tolkien" },
		coverPath: "/assets/book-covers/senhor-dos-aneis.png",
		price: 89.9,

		resume:
			"Frodo Bolseiro herda um anel mágico de seu tio Bilbo, descobrindo que se trata do Um Anel forjado pelo Senhor Sombrio Sauron para controlar todos os outros anéis de poder. Com a ajuda da Sociedade do Anel, formada por hobbits, elfos, anões, homens e um mago, Frodo embarca em uma perigosa jornada para destruir o anel no Monte da Perdição, única forma de derrotar Sauron e salvar a Terra-média.",
		isbn: "978-85-7657-009-8",
		numberOfPages: 1216,
		categories: ["Fantasia Épica", "Literatura Clássica"],
		year: 1954,
		edition: "3a. edição",
		publisher: { _description: "HarperCollins" },
		height: 23.0,
		width: 15.0,
		weight: 1.2,
		thickness: 6.0,
		barCode: "9788576570098",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 4,
		name: "Crepúsculo",
		author: { _name: "Stephenie Meyer" },
		coverPath: "/assets/book-covers/crepusculo.png",
		price: 34.9,

		resume:
			"Bella Swan se muda para a cidade chuvosa de Forks, Washington, onde conhece Edward Cullen, um jovem misterioso e atraente. Ela descobrirá que Edward é um vampiro de mais de cem anos que luta contra seus instintos predatórios para protegê-la. Seu amor impossível será testado por outros vampiros que ameaçam a vida de Bella, iniciando uma saga de romance sobrenatural que mudou o gênero para sempre.",
		isbn: "978-85-98078-62-7",
		numberOfPages: 424,
		categories: ["Romance Paranormal", "Romance Moderno"],
		year: 2005,
		edition: "5a. edição",
		publisher: { _description: "Intrínseca" },
		height: 20.5,
		width: 13.5,
		weight: 0.45,
		thickness: 2.2,
		barCode: "9788598078627",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 5,
		name: "É Assim que Acaba",
		author: { _name: "Colleen Hoover" },
		coverPath: "/assets/book-covers/e-assim-que-acaba.png",
		price: 44.9,

		resume:
			"Lily Bloom sempre sonhou em ter sua própria floricultura em Boston. Quando conhece Ryle, um neurocirurgião charmoso, parece que encontrou o amor da sua vida. Porém, quando Atlas, seu primeiro amor, reaparece, Lily se vê confrontada com seu passado e forçada a tomar decisões difíceis sobre seu futuro. Uma história poderosa sobre amor, coragem e a força necessária para romper ciclos destrutivos.",
		isbn: "978-85-01-11347-7",
		numberOfPages: 368,
		categories: ["Romance Dramático", "Romance Moderno"],
		year: 2016,
		edition: "7a. edição",
		publisher: { _description: "Galera Record" },
		height: 20.5,
		width: 13.5,
		weight: 0.4,
		thickness: 2.0,
		barCode: "9788501113477",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 6,
		name: "Noites Brancas",
		author: { _name: "Fiódor Dostoiévski" },
		coverPath: "/assets/book-covers/noites-brancas.png",
		price: 29.9,

		resume:
			"Um jovem solitário vaga pelas ruas de São Petersburgo durante as famosas noites brancas do verão russo. Ele conhece Nastenka, uma jovem que espera pelo retorno de seu amado. Durante quatro noites consecutivas, eles compartilham histórias, sonhos e uma conexão profunda. Esta novela melancólica explora temas de solidão, amor não correspondido e a natureza efêmera dos encontros humanos.",
		isbn: "978-85-254-1789-4",
		numberOfPages: 96,
		categories: ["Literatura Russa"],
		year: 1848,
		edition: "2a. edição",
		publisher: { _description: "L&PM" },
		height: 18.0,
		width: 12.0,
		weight: 0.15,
		thickness: 0.8,
		barCode: "9788525417894",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 7,
		name: "1984",
		author: { _name: "George Orwell" },
		coverPath: "/assets/book-covers/1984.png",
		price: 42.9,

		resume:
			"Winston Smith vive em uma sociedade totalitária onde o Grande Irmão observa todos os movimentos dos cidadãos. Trabalhando no Ministério da Verdade, ele altera documentos históricos para servir aos interesses do Partido. Quando se apaixona por Julia, Winston inicia uma jornada de rebelião que o colocará face a face com as forças mais sombrias do regime. Uma distopia visionária sobre vigilância, controle e a natureza da verdade.",
		isbn: "978-85-359-0277-8",
		numberOfPages: 416,
		categories: ["Ficção Distópica", "Literatura Clássica"],
		year: 1948,
		edition: "4a. edição",
		publisher: { _description: "Companhia das Letras" },
		height: 20.5,
		width: 13.5,
		weight: 0.45,
		thickness: 2.2,
		barCode: "9788535902778",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 8,
		name: "O Pequeno Príncipe",
		author: { _name: "Antoine de Saint-Exupéry" },
		coverPath: "/assets/book-covers/o-pequeno-principe.png",
		price: 24.9,

		resume:
			"Um piloto perdido no deserto do Saara encontra um pequeno príncipe de outro planeta. Através de suas conversas, o menino conta sobre sua jornada por diferentes planetas e os adultos estranhos que encontrou. Com sua perspectiva inocente, ele questiona o mundo adulto e suas prioridades. Uma fábula atemporal sobre amizade, amor, perda e o que realmente importa na vida.",
		isbn: "978-85-220-0778-5",
		numberOfPages: 96,
		categories: ["Literatura Infantojuvenil", "Literatura Clássica"],
		year: 1943,
		edition: "8a. edição",
		publisher: { _description: "HarperCollins" },
		height: 18.0,
		width: 12.0,
		weight: 0.15,
		thickness: 0.8,
		barCode: "9788522007785",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 9,
		name: "Dom Casmurro",
		author: { _name: "Machado de Assis" },
		coverPath: "/assets/book-covers/dom-casmurro.png",
		price: 35.9,

		resume:
			"Bentinho narra a história de seu amor de infância por Capitu, sua vizinha de olhos de ressaca. Destinado ao seminário por uma promessa de sua mãe, ele luta para escapar da vida religiosa e casar com seu grande amor. Anos depois, consumido pelo ciúme, ele suspeita que Capitu o traiu com seu melhor amigo Escobar. A narrativa ambígua deixa ao leitor a tarefa de decifrar a verdade sobre a suposta traição.",
		isbn: "978-85-359-0123-6",
		numberOfPages: 256,
		categories: ["Literatura Brasileira", "Literatura Clássica"],
		year: 1899,
		edition: "6a. edição",
		publisher: { _description: "Companhia das Letras" },
		height: 20.5,
		width: 13.5,
		weight: 0.3,
		thickness: 1.5,
		barCode: "9788535901236",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 10,
		name: "O Cortiço",
		author: { _name: "Aluísio Azevedo" },
		coverPath: "/assets/book-covers/o-cortico.png",
		price: 38.9,

		resume:
			"João Romão, um comerciante português ambicioso, constrói um cortiço no Rio de Janeiro do século XIX. O livro retrata a vida dos moradores deste ambiente promíscuo e degradante, mostrando como o meio social influencia o comportamento humano. Através das histórias entrelaçadas de seus habitantes, Azevedo critica as desigualdades sociais e apresenta um panorama realista da sociedade brasileira da época.",
		isbn: "978-85-254-2156-3",
		numberOfPages: 304,
		categories: ["Literatura Brasileira", "Literatura Clássica"],
		year: 1890,
		edition: "3a. edição",
		publisher: { _description: "Martin Claret" },
		height: 20.5,
		width: 13.5,
		weight: 0.35,
		thickness: 1.8,
		barCode: "9788525421563",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 11,
		name: "Cem Anos de Solidão",
		author: { _name: "Gabriel García Márquez" },
		coverPath: "/assets/book-covers/cem-anos-de-solidao.png",
		price: 54.9,

		resume:
			"A saga da família Buendía na mítica cidade de Macondo, fundada por José Arcadio Buendía. Através de sete gerações, acompanhamos amores impossíveis, guerras intermináveis, descobertas científicas e eventos mágicos que se misturam ao cotidiano. Uma obra-prima do realismo mágico que retrata a história da América Latina através da história de uma família marcada pela solidão e por destinos que se repetem ciclicamente.",
		isbn: "978-85-359-0445-9",
		numberOfPages: 432,
		categories: ["Realismo Mágico", "Literatura Clássica"],
		year: 1967,
		edition: "2a. edição",
		publisher: { _description: "Record" },
		height: 20.5,
		width: 13.5,
		weight: 0.5,
		thickness: 2.3,
		barCode: "9788535904459",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 12,
		name: "O Sol é Para Todos",
		author: { _name: "Harper Lee" },
		coverPath: "/assets/book-covers/o-sol-e-para-todos.png",
		price: 47.9,

		resume:
			"Scout Finch narra sua infância no Alabama dos anos 1930, quando seu pai, o advogado Atticus Finch, defende um homem negro falsamente acusado de estupro. Através dos olhos de uma criança, vemos os preconceitos e injustiças de uma sociedade segregada. A história explora temas de moralidade, crescimento e coragem moral em uma América dividida pelo racismo.",
		isbn: "978-85-01-08994-8",
		numberOfPages: 392,
		categories: ["Literatura Americana", "Literatura Clássica"],
		year: 1960,
		edition: "9a. edição",
		publisher: { _description: "José Olympio" },
		height: 20.5,
		width: 13.5,
		weight: 0.4,
		thickness: 2.0,
		barCode: "9788501089948",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 13,
		name: "Orgulho e Preconceito",
		author: { _name: "Jane Austen" },
		coverPath: "/assets/book-covers/orgulho-e-preconceito.png",
		price: 41.9,

		resume:
			"Elizabeth Bennet é uma jovem inteligente e independente na Inglaterra georgiana. Quando conhece o rico e aparentemente arrogante Sr. Darcy, forma uma primeira impressão negativa. Através de mal-entendidos, revelações e crescimento pessoal, ambos descobrem que suas percepções iniciais estavam erradas. Uma comédia de costumes sobre amor, classe social e a importância de olhar além das aparências.",
		isbn: "978-85-254-3247-7",
		numberOfPages: 424,
		categories: ["Romance Clássico", "Literatura Clássica"],
		year: 1813,
		edition: "5a. edição",
		publisher: { _description: "Penguin Companhia" },
		height: 20.5,
		width: 13.5,
		weight: 0.45,
		thickness: 2.2,
		barCode: "9788525432477",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 14,
		name: "A Metamorfose",
		author: { _name: "Franz Kafka" },
		coverPath: "/assets/book-covers/a-metamorfose.png",
		price: 32.9,

		resume:
			"Gregor Samsa acorda uma manhã transformado em um inseto gigantesco. Esta transformação física reflete sua alienação do trabalho, da família e da sociedade. Confinado em seu quarto, ele observa como sua condição afeta a dinâmica familiar e questiona sua própria humanidade. Uma alegoria poderosa sobre isolamento, desumanização e as pressões da vida moderna.",
		isbn: "978-85-359-0156-4",
		numberOfPages: 104,
		categories: ["Literatura Moderna", "Literatura Clássica"],
		year: 1915,
		edition: "4a. edição",
		publisher: { _description: "Companhia das Letras" },
		height: 18.0,
		width: 12.0,
		weight: 0.15,
		thickness: 0.8,
		barCode: "9788535901564",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 15,
		name: "Os Miseráveis",
		author: { _name: "Victor Hugo" },
		coverPath: "/assets/book-covers/os-miseraveis.png",
		price: 67.9,

		resume:
			"Jean Valjean, um ex-presidiário em busca de redenção, luta para reconstruir sua vida na França do século XIX. Perseguido pelo implacável inspetor Javert, ele adota Cosette, filha da operária Fantine, e tenta protegê-la das injustiças sociais. Ambientado durante os tumultos políticos franceses, o romance explora temas de justiça, amor, sacrifício e a possibilidade de transformação humana.",
		isbn: "978-85-220-1445-5",
		numberOfPages: 1488,
		categories: ["Literatura Francesa", "Literatura Clássica"],
		year: 1862,
		edition: "7a. edição",
		publisher: { _description: "Cosac Naify" },
		height: 23.0,
		width: 15.0,
		weight: 1.5,
		thickness: 7.0,
		barCode: "9788522014455",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 16,
		name: "O Grande Gatsby",
		author: { _name: "F. Scott Fitzgerald" },
		coverPath: "/assets/book-covers/o-grande-gatsby.png",
		price: 39.9,

		resume:
			"Nick Carraway narra a história de seu misterioso vizinho Jay Gatsby, que oferece festas extravagantes em sua mansão de Long Island na esperança de reconquistar seu amor perdido, Daisy Buchanan. Ambientado nos loucos anos 1920, o romance explora a decadência moral da alta sociedade americana, o sonho americano e a impossibilidade de repetir o passado.",
		isbn: "978-85-01-09847-6",
		numberOfPages: 224,
		categories: ["Literatura Americana", "Literatura Clássica"],
		year: 1925,
		edition: "6a. edição",
		publisher: { _description: "L&PM" },
		height: 20.5,
		width: 13.5,
		weight: 0.3,
		thickness: 1.5,
		barCode: "9788501098476",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 17,
		name: "Moby Dick",
		author: { _name: "Herman Melville" },
		coverPath: "/assets/book-covers/moby-dick.png",
		price: 59.9,

		resume:
			"Ishmael embarca no navio baleeiro Pequod, comandado pelo capitão Ahab. Obcecado pela baleia branca que destruiu seu navio anterior e arrancou sua perna, Ahab transforma a viagem comercial em uma busca pessoal por vingança. A narrativa épica explora temas de obsessão, natureza, destino e a luta do homem contra forças maiores que ele próprio.",
		isbn: "978-85-359-1278-2",
		numberOfPages: 704,
		categories: ["Literatura Americana", "Literatura Clássica"],
		year: 1851,
		edition: "3a. edição",
		publisher: { _description: "Penguin Companhia" },
		height: 21.0,
		width: 14.0,
		weight: 0.7,
		thickness: 3.5,
		barCode: "9788535912782",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 18,
		name: "Romeu e Julieta",
		author: { _name: "William Shakespeare" },
		coverPath: "/assets/book-covers/romeu-e-julieta.png",
		price: 28.9,

		resume:
			"Em Verona, duas famílias nobres, os Montecchios e os Capuletos, mantêm uma rivalidade antiga. Romeu Montecchio e Julieta Capuleto se apaixonam perdidamente e se casam em segredo. Quando Romeu mata Teobaldo, primo de Julieta, numa briga, ele é banido da cidade. A tentativa desesperada dos jovens amantes de ficarem juntos leva a uma tragédia que finalmente reconcilia as famílias rivais.",
		isbn: "978-85-254-0891-5",
		numberOfPages: 160,
		categories: ["Teatro Clássico", "Literatura Clássica", "Romance Clássico"],
		year: 1595,
		edition: "10a. edição",
		publisher: { _description: "Martin Claret" },
		height: 18.0,
		width: 12.0,
		weight: 0.2,
		thickness: 1.0,
		barCode: "9788525408915",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 19,
		name: "Anna Karênina",
		author: { _name: "Lev Tolstói" },
		coverPath: "/assets/book-covers/anna-karenina.png",
		price: 72.9,

		resume:
			"Anna Karênina, esposa de um alto funcionário russo, se apaixona pelo conde Vronsky e abandona marido e filho para viver este amor proibido. Paralelamente, acompanhamos Konstantin Levin em sua busca pelo sentido da vida através do trabalho na terra e do amor por Kitty. Tolstói retrata com maestria a aristocracia russa do século XIX e explora questões morais, sociais e espirituais profundas.",
		isbn: "978-85-359-2134-0",
		numberOfPages: 992,
		categories: ["Literatura Russa", "Literatura Clássica", "Romance Clássico"],
		year: 1877,
		edition: "4a. edição",
		publisher: { _description: "Companhia das Letras" },
		height: 22.0,
		width: 14.5,
		weight: 1.0,
		thickness: 5.0,
		barCode: "9788535921340",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
	{
		id: 20,
		name: "Lolita",
		author: { _name: "Vladimir Nabokov" },
		coverPath: "/assets/book-covers/lolita.png",
		price: 49.9,

		resume:
			"Humbert Humbert, um professor de literatura de meia-idade, desenvolve uma obsessão pela filha de 12 anos de sua senhoria, Dolores Haze, a quem chama de Lolita. Narrando da prisão, Humbert conta como seduziu a mãe da garota, casou-se com ela e, após sua morte, fugiu com Lolita numa viagem pelos Estados Unidos. Uma obra controversa que explora temas de obsessão, manipulação e a natureza sedutora da linguagem.",
		isbn: "978-85-359-0987-4",
		numberOfPages: 432,
		categories: ["Literatura Moderna", "Literatura Americana"],
		year: 1955,
		edition: "2a. edição",
		publisher: { _description: "Companhia das Letras" },
		height: 20.5,
		width: 13.5,
		weight: 0.45,
		thickness: 2.2,
		barCode: "9788535909874",
		inactivationCause: "",
		activationCause: "Lançamento",
	},
];

export default books;
